apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent-config-cloud
  namespace: default
  labels:
    component: ip-masq-agent
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
data:
  ip-masq-agent-cloud: |-
    nonMasqueradeCIDRs:
      - 1.0.0.0/8
      - 2.2.0.0/16
      - 3.3.3.0/24
    masqLinkLocal: true