name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args:
            -v
            --max-same-issues 10
            --disable-all
            --exclude-use-default=false
            -E asciicheck
            -E errcheck
            -E forcetypeassert
            -E gocritic
            -E gofmt
            -E goimports
            -E gosimple
            -E govet
            -E ineffassign
            -E misspell
            -E staticcheck
            -E typecheck
            -E unused
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          make build
        name: Build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          make test
        name: Test
