name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # v2.5.2
        with:
          version: latest
          args:
            -v
            --max-same-issues 10
            --disable-all
            --exclude-use-default=false
            -E asciicheck
            -E errcheck
            -E forcetypeassert
            -E gocritic
            -E gofmt
            -E goimports
            -E gosimple
            -E govet
            -E ineffassign
            -E misspell
            -E staticcheck
            -E typecheck
            -E unused
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - run: |
          make build
        name: Build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - run: |
          make test
        name: Test
